# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.IntegerField(choices=[(0, 'Pending...'), (1, 'Negotiating'), (2, 'Accepted'), (3, 'Completed'), (4, 'Canceled')], default=0),
        ),
    ]
