# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20160323_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
