# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20160118_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
