# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20160227_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Negotiating'), (2, 'Accepted'), (3, 'Completed')], default=0),
        ),
    ]
