# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20160428_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.IntegerField(choices=[(0, 'Pending...'), (1, 'Negotiating'), (2, 'Accepted'), (3, 'Completed'), (4, 'Canceled'), (5, 'Select Driver')], default=0),
        ),
    ]
