# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20160428_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pick_up_interval',
            field=models.TimeField(default=datetime.datetime(2016, 5, 5, 16, 40, 33, 282989)),
        ),
    ]
