# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20160505_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pick_up_interval',
            field=models.TimeField(default=datetime.datetime(2016, 5, 5, 16, 51, 8, 669093)),
        ),
    ]
