# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20160505_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pick_up_interval',
            field=models.TimeField(),
        ),
    ]
