# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 15:56
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='email')),
                ('full_name', models.CharField(default='Temporary Name', max_length=120)),
                ('profile_picture', models.ImageField(blank=True, upload_to=accounts.models.upload_location)),
                ('phone_number', models.CharField(blank=True, max_length=18)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('car_make', models.CharField(blank=True, max_length=30)),
                ('car_model', models.CharField(blank=True, max_length=30)),
                ('car_status', models.IntegerField(choices=[(0, 'New'), (1, 'Good'), (2, 'Fair'), (3, 'Poor')], default=0)),
                ('license_plate', models.CharField(blank=True, max_length=12)),
                ('rating', models.IntegerField(default=0)),
                ('trips_completed', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
