# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 23:34
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160408_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/img/default-no-profile-pic.jpg', upload_to=accounts.models.upload_location),
        ),
    ]
