# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160202_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('rating', models.IntegerField(default=0, null=True)),
                ('trips_completed', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
