# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='trips_completed',
            field=models.IntegerField(default=0),
        ),
    ]
