# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apnsdevice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gcmdevice',
            name='name',
        ),
        migrations.AddField(
            model_name='apnsdevice',
            name='device_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='gcmdevice',
            name='device_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device'),
        ),
    ]
