# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0002_auto_20160105_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apnsdevice',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='gcmdevice',
            old_name='active',
            new_name='is_active',
        ),
    ]
