# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import push_notifications.fields


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0003_auto_20160105_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnsdevice',
            name='registration_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='Registration ID'),
        ),
        migrations.AlterField(
            model_name='gcmdevice',
            name='device_id',
            field=push_notifications.fields.HexIntegerField(blank=True, db_index=True, help_text='ANDROID_ID / TelephonyManager.getDeviceId()', null=True, verbose_name='Device ID'),
        ),
    ]
